# Generated by Django 2.1.4 on 2019-03-04 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educator', '0008_plans_validity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoutsRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Read At')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Exams', verbose_name='Exam ID')),
                ('handout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Handout', verbose_name='Handout ID')),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Notes', verbose_name='Notes ID')),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handout_read_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handout Reads',
                'verbose_name_plural': 'Handout Reads',
                'ordering': ('read_at',),
            },
        ),
        migrations.CreateModel(
            name='LecturesWatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Watched At')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Exams', verbose_name='Exam ID')),
                ('lect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.VideoLectures', verbose_name='Video Lecture ID')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Videos', verbose_name='Video Related to')),
                ('watched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_watched_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture Views',
                'verbose_name_plural': 'Lectures Views',
                'ordering': ('watched_at',),
            },
        ),
        migrations.CreateModel(
            name='OTSAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(default=0.0)),
                ('correct_marks', models.FloatField(default=0.0)),
                ('negative_marks', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Exam started At')),
                ('attempt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempted_by', to=settings.AUTH_USER_MODEL)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Exams', verbose_name='Exam ID')),
                ('ots_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots_id', to='educator.OnlineExams')),
            ],
            options={
                'verbose_name': 'OTS Attempt',
                'verbose_name_plural': 'OTS Attempt',
                'ordering': ('started_at',),
            },
        ),
        migrations.CreateModel(
            name='OTSsubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_get', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted at')),
                ('attempt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots_attempted_by', to=settings.AUTH_USER_MODEL)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Exams', verbose_name='Exam ID')),
                ('ots_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otsattempt_ots_id', to='educator.OnlineExams')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Questions')),
            ],
            options={
                'verbose_name': 'OTS Submissions',
                'verbose_name_plural': 'OTS Submissions',
                'ordering': ('submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted at')),
                ('attempt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempted_by', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educator.Questions')),
            ],
            options={
                'verbose_name': 'Quiz Submissions',
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ('submitted_at',),
            },
        ),
    ]
