# Generated by Django 2.1.4 on 2019-02-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name of Educator')),
                ('phone_number', models.CharField(default=0, max_length=15, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('unique_referral_code', models.CharField(blank=True, default='', editable=False, max_length=12, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='static/users/profile_pic', verbose_name='Profile Picture')),
                ('dob', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('education', models.CharField(blank=True, default='', max_length=255)),
                ('default_lang', models.IntegerField(choices=[(1, 'English'), (2, 'Hindi')], default=1, verbose_name='Default Lang for Exams')),
                ('is_educator', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('access_level', models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'Moderator'), (4, 'Editor'), (5, 'Content Writer'), (6, 'Accounts'), (7, 'Others'), (8, 'Educator'), (9, 'Student')], default=7, verbose_name='Access level')),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User Profile',
                'ordering': ('email',),
            },
        ),
    ]
