# Generated by Django 2.1.4 on 2019-02-20 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255, verbose_name='Exam Category Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Name',
                'verbose_name_plural': 'Categries Name',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='', max_length=255, verbose_name='Exam Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_created_by', to=settings.AUTH_USER_MODEL)),
                ('exam_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_category', to='educator.ExamCategory')),
            ],
            options={
                'verbose_name': 'Exam Name',
                'verbose_name_plural': 'Exams Name',
                'ordering': ('exam_name',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(default='', max_length=120, verbose_name='Payment done for')),
                ('payment_amount', models.FloatField(default=0, verbose_name='Payment amount')),
                ('payment_id', models.CharField(default='', max_length=120, verbose_name='Payment ID')),
                ('payment_gateway', models.CharField(default='', max_length=120, verbose_name='Payment gateway')),
                ('payment_status', models.CharField(default='', max_length=120, verbose_name='Payment status')),
                ('bank_ref_num', models.CharField(default='', max_length=120, verbose_name='Payment Bank Ref. Number')),
                ('pg_type', models.CharField(default='', max_length=120, verbose_name='Payment PG Type')),
                ('pay_mode', models.CharField(default='', max_length=120, verbose_name='Payment Mode')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment done on')),
                ('expire_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Plan will expire on')),
                ('verification_code', models.CharField(default='', max_length=120, verbose_name='Any Verification code')),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
                'ordering': ('payment_id',),
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='', max_length=255, verbose_name='Plan Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Price of the Plan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_created_by', to=settings.AUTH_USER_MODEL)),
                ('exams', models.ManyToManyField(blank=True, to='educator.Exams')),
            ],
            options={
                'verbose_name': 'Plan Name',
                'verbose_name_plural': 'Plan Name',
                'ordering': ('plan_name',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plans', to='educator.Plans'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
