# Generated by Django 2.1.4 on 2019-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='educator.Subjects'),
        ),
    ]
