# Generated by Django 2.1.4 on 2019-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0005_auto_20190221_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcategory',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='exams',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='handout',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='notes',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='onlineexams',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='topics',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='videolectures',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='videos',
            name='is_deleted',
            field=models.BooleanField(default=True, verbose_name='is deleted?'),
        ),
    ]
