# Generated by Django 2.1.4 on 2019-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0007_auto_20190303_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='validity',
            field=models.IntegerField(default=90, verbose_name='Plan Validity(In Days)'),
        ),
    ]
