# Generated by Django 2.1.4 on 2019-03-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0008_plans_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='topics',
        ),
        migrations.AddField(
            model_name='videos',
            name='topics',
            field=models.ManyToManyField(to='educator.Topics', verbose_name='Topics video related to'),
        ),
    ]
