# Generated by Django 2.1.4 on 2019-03-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0009_auto_20190306_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handout',
            name='topics',
        ),
        migrations.AddField(
            model_name='handout',
            name='topics',
            field=models.ManyToManyField(to='educator.Topics', verbose_name='Topics video related to'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='topics',
        ),
        migrations.AddField(
            model_name='questions',
            name='topics',
            field=models.ManyToManyField(to='educator.Topics', verbose_name='Topics video related to'),
        ),
    ]
