# Generated by Django 2.1.4 on 2019-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0010_auto_20190306_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
