# Generated by Django 2.1.7 on 2019-04-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0012_plans_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptions',
            name='hindi_option_title',
            field=models.TextField(default='', verbose_name='Hindi Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='hindi_question',
            field=models.TextField(default='', verbose_name='Question in Hindi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='hindi_solution',
            field=models.TextField(default='', verbose_name='Solution in Hindi'),
            preserve_default=False,
        ),
    ]
