# Generated by Django 2.1.7 on 2019-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0013_auto_20190405_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexams',
            name='expire_on',
            field=models.DateTimeField(default='', verbose_name='Online Exam Will expire on??'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='expire_on',
            field=models.DateTimeField(default='', verbose_name='Online Quiz Will expire on??'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Test Duration(In Minutes)'),
        ),
    ]
