# Generated by Django 2.1.7 on 2019-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0014_auto_20190408_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineexams',
            name='expire_on',
            field=models.DateTimeField(default='2020-01-01 23:55:55', verbose_name='Online Exam Will expire on??'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='expire_on',
            field=models.DateTimeField(default='2020-01-01 23:55:55', verbose_name='Online Quiz Will expire on??'),
        ),
    ]
