# Generated by Django 2.1.7 on 2019-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0015_auto_20190408_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexams',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Is Online Exam is Available Freely??'),
        ),
        migrations.AddField(
            model_name='onlineexams',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects_related_to_ots', to='educator.Subjects', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='questions',
            name='avg_time',
            field=models.IntegerField(default=10, verbose_name='Average Solving Time(in seconds)'),
        ),
        migrations.AddField(
            model_name='questions',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert')], default=1, verbose_name='Question Difficulty Level'),
        ),
    ]
